<a href="https://colab.research.google.com/github/Lazysheep2031/Pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [3]:
my_list=[[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [5]:
np1 = np.random.rand(4,5)
np1

array([[0.29332944, 0.96568119, 0.6223693 , 0.34344176, 0.85055825],
       [0.1919878 , 0.92766439, 0.58761264, 0.54533289, 0.30505677],
       [0.63519873, 0.33372707, 0.87488889, 0.00537984, 0.42634431],
       [0.07196933, 0.23829746, 0.19612745, 0.47288309, 0.34310475]])

In [6]:
 np1.dtype

dtype('float64')

In [13]:
tensor_2d =torch.rand(4,5)
tensor_2d

tensor([[0.4955, 0.1097, 0.6873, 0.6881, 0.2214],
        [0.4403, 0.5860, 0.4078, 0.4542, 0.0791],
        [0.4606, 0.6157, 0.6694, 0.0907, 0.1457],
        [0.3504, 0.9076, 0.0437, 0.1978, 0.5011]])

In [14]:
tensor_2d.dtype

torch.float32

In [16]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [17]:
#Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2933, 0.9657, 0.6224, 0.3434, 0.8506],
        [0.1920, 0.9277, 0.5876, 0.5453, 0.3051],
        [0.6352, 0.3337, 0.8749, 0.0054, 0.4263],
        [0.0720, 0.2383, 0.1961, 0.4729, 0.3431]], dtype=torch.float64)